# Generated by Django 5.1.1 on 2024-09-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
